AllCops:
  RunRailsCops: true
  Exclude:
    - app/controllers/application_controller.rb
    - app/controllers/notes_controller.rb:
    - bin/*
    - app/helpers/**/*
    - app/models/note.rb
    - config/**/*
    - db/schema.rb
    - db/seeds.rb
    - db/migrate/*.rb
    - lib/**/*
    - Rakefile
    - spec/i18n_spec.rb
    - spec/rails_helper.rb
    - spec/spec_helper.rb
    - Gemfile
    - Gemfile.lock
